GH Actions: downgrade Ruby 1.9 job to Ubuntu 22.04
It seems that Ruby 1.9 cannot be downloaded on Ubuntu 24.04 using the
`ruby/setup-ruby@v1` action, see the CI error when we tried it:

```
Run ruby/setup-ruby@v1
  with:
    ruby-version: 1.9
    bundler-cache: true
Modifying PATH
  Entries added to PATH to use selected Ruby:
    /opt/hostedtoolcache/Ruby/1.9.3-p551/x64/bin
Downloading Ruby
  https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-1.9.3-p551-ubuntu-24.04.tar.gz
  Took   0.25 seconds
Error: Unavailable version 1.9.3-p551 for ruby on ubuntu-24.04
          You can request it at https://github.com/ruby/setup-ruby/issues
          Cause: Unexpected HTTP response: 404
    at /home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:74112:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async body (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:355:14)
```